#!/usr/bin/env python3
r"""TASK-0001 Stage B — published-phenomenon reproduction: reachable present-state
non-injectivity of an autonomous Caputo system in d = 2.

WHAT IS AND IS NOT CLAIMED
--------------------------
The *phenomenon* to be reproduced is the one recorded as KNOWN-A02 in
research/CLAIMS.md: Cong & Tuan (2017) prove scalar non-intersection but
construct higher-dimensional autonomous Caputo systems in which trajectories
from distinct standard initial data intersect at finite time, so that
``e_0 : R_alpha -> X_phys`` need not be injective.

**The text of Cong & Tuan (2017) is not available inside this repository** (only
the reference entry and prose summaries).  The construction below was therefore
derived independently by the Compute Agent and is *not* verified to be the
published example.  It is labelled PROJECT-CONSTRUCTED, and Stage B's purpose
is met either way: it supplies an exactly solvable two-dimensional collision
with certified ground truth against which the collision-detection and
root-refinement machinery is calibrated.  No novelty is claimed: linear
Caputo systems and the zeros of the Mittag-Leffler function are classical.

THE CONSTRUCTION
----------------
For ``^C D^alpha x = A x`` the solution is exactly ``x(t) = E_alpha(A t^alpha) x0``.
Let ``z`` be any non-real zero of ``E_alpha`` and set

    A = [[Re z, -Im z], [Im z, Re z]]      (so A = |z| R(arg z), eigenvalues z, conj z)

The algebra generated by ``I`` and ``J = [[0,-1],[1,0]]`` is isomorphic to C, so
with ``w = E_alpha(z t^alpha)``

    E_alpha(A t^alpha) = [[Re w, -Im w], [Im w, Re w]],
    det E_alpha(A t^alpha) = |w|^2 .

At ``t = 1`` we get ``w = E_alpha(z) = 0``, hence ``E_alpha(A) = 0`` as a matrix and

    x(1; x0) = 0   for EVERY x0 in R^2 .

So ``e_0 . T_1`` is *constant* on the reachable set: present-state observation at
time 1 is maximally non-injective.  This is the strongest possible form of
KNOWN-A02 and it is exact algebra once a zero of ``E_alpha`` is known.

For ``0 < alpha < 1`` with ``1/alpha`` non-integer, ``E_alpha`` has order
``1/alpha > 1`` and non-integral order, so by Hadamard factorisation it has
infinitely many zeros; for ``alpha = 1/2`` the closed form
``E_{1/2}(z) = e^{z^2} erfc(-z)`` gives them from the zeros of ``erfc``.
This script certifies one such zero by a Krawczyk test in Arb ball arithmetic
and then confirms the predicted collapse with all three solvers.
"""
from __future__ import annotations

import os
import sys

import mpmath as mp
import numpy as np
from flint import acb, arb

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from msbg.certify import e_alpha_ball, krawczyk_certify_zero_auto     # noqa: E402
from msbg.collisions import collision_jacobian, cross_age_collisions  # noqa: E402
from msbg.mittag_leffler import e_alpha, e_alpha_closed_form, e_alpha_zero  # noqa: E402
from msbg.models import ScaledRotation                               # noqa: E402
from msbg.provenance import RunRecorder, set_seed                    # noqa: E402
from msbg.solvers import METHODS, solve, solve_mp                    # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALPHA = 0.5


def locate_zero():
    """Locate the first non-real zero of E_{1/2} by two independent routes."""
    mp.mp.dps = 50
    w = mp.findroot(mp.erfc, mp.mpc("-1.35", "1.99"))       # route 1: closed form
    z_closed = -w
    z_own = e_alpha_zero(ALPHA, mp.mpc("1.3548", "-1.9915"), dps=40)  # route 2: own series
    return z_closed, z_own, abs(z_closed - z_own)


def main():
    set_seed()
    np.seterr(all="ignore")
    rec = RunRecorder("stage_b", ROOT)

    # ---------------- B1: the zero, two independent routes ------------------
    z_closed, z_own, agree = locate_zero()
    print(f"B1 zero of E_1/2:\n    via erfc closed form : {mp.nstr(z_closed, 30)}")
    print(f"    via own Taylor Newton: {mp.nstr(z_own, 30)}")
    print(f"    agreement            : {mp.nstr(agree, 4)}")
    rec.add("B1_zero_closed_form", str(mp.nstr(z_closed, 30)))
    rec.add("B1_zero_own_newton", str(mp.nstr(z_own, 30)))
    rec.add("B1_route_agreement", float(mp.nstr(agree, 6)))

    # ---------------- B2: Krawczyk certification ----------------------------
    cz, box, attempts = krawczyk_certify_zero_auto(
        ALPHA, acb(str(mp.re(z_closed)), str(mp.im(z_closed))), K=200, prec=600
    )
    assert cz is not None, f"Krawczyk certification failed at every radius: {attempts}"
    rec.add("B2_krawczyk_radius_ladder", attempts)
    print("B2 CERTIFIED unique zero in box:")
    print(f"    Re z* in {cz.box_re}")
    print(f"    Im z* in {cz.box_im}")
    rec.add("B2_certified_zero", cz.as_dict())
    # rigorous enclosure of E_alpha on the certified box: must contain 0
    val = e_alpha_ball(ALPHA, box, K=200, prec=600)
    rec.add("B2_E_alpha_on_box", {"real": str(val.real), "imag": str(val.imag),
                                  "contains_zero": bool(arb(0) in val.real and arb(0) in val.imag)})
    print(f"    E_a(box) = {val}  contains 0: {rec.results['B2_E_alpha_on_box']['contains_zero']}")

    # ---------------- B3: the model and its exact prediction ----------------
    re_z, im_z = float(mp.re(z_closed)), float(mp.im(z_closed))
    rho, theta = float(abs(z_closed)), float(mp.arg(z_closed))
    model = ScaledRotation(rho=rho, theta=theta)
    print(f"B3 A = {model.A.tolist()}   (rho={rho:.15f}, theta={theta:.15f})")
    print("    exact prediction: x(1; x0) = 0 for every x0")
    rec.add("B3_matrix_A", model.A.tolist())
    rec.add("B3_rho", rho)
    rec.add("B3_theta", theta)
    rec.add("B3_collision_time_exact", 1.0)

    # ---------------- B4: three-solver confirmation of the collapse ---------
    X0 = np.array([[1.0, 0.0], [0.0, 1.0], [2.0, -3.0], [0.37, 0.91], [-1.5, 0.25]])
    ladder = (1000, 2000, 4000, 8000, 16000, 32000)
    b4 = []
    for method in METHODS:
        errs = []
        for N in ladder:
            r = solve(model, X0, ALPHA, 1.0 / N, N, method=method, store=False)
            errs.append(float(np.max(np.abs(r.x_final))))
        A = np.vstack([np.log(1.0 / np.array(ladder, float)), np.ones(len(ladder))]).T
        slope = float(np.linalg.lstsq(A, np.log(errs), rcond=None)[0][0])
        b4.append({"method": method, "N": list(ladder), "max_abs_x_at_t1": errs,
                   "observed_order": slope})
        print(f"B4 {method:8} |x(1)| finest = {errs[-1]:.3e}   observed order = {slope:.3f}")
    rec.save_json("B4_collapse_convergence", b4)

    # ---------------- B5: high-precision single trajectory -------------------
    traj_mp = solve_mp(model.g_mp, [1.0, 0.0], ALPHA, mp.mpf(1) / 4000, 4000, dps=30, method="pece")
    endpt = traj_mp[-1]
    print(f"B5 mpmath PECE (dps=30, N=4000): x(1) = "
          f"({mp.nstr(endpt[0],8)}, {mp.nstr(endpt[1],8)})")
    rec.add("B5_mp_endpoint", [str(mp.nstr(v, 12)) for v in endpt])

    # ---------------- B6: collision detection machinery on known truth ------
    # Two distinct initial data; their orbits must meet at t = s = 1 (both at 0).
    r = solve(model, X0[:2], ALPHA, 1.2 / 24000, 24000, method="pece", store=True,
              store_stride=20)
    hits = cross_age_collisions(r.t, r.x[:, 0, :], r.x[:, 1, :], max_hits=20)
    print(f"B6 polyline crossings detected: {len(hits)}")
    for tc, sc, xc, ca in hits[:6]:
        print(f"    t={tc:.6f} s={sc:.6f} x={np.array(xc)}  cos(angle)={ca:+.4f}")
    rec.save_json("B6_detected_crossings",
                  [{"t": t, "s": s, "x": list(x), "cos_angle": c} for t, s, x, c in hits])

    # ---------------- B7: degeneracy of the linear collision -----------------
    # d x(t;p)/dp = E_alpha(A t^alpha) = 0 at t = 1: the collision is MAXIMALLY
    # degenerate in the initial states and non-degenerate only in the ages.
    J = collision_jacobian(model, X0[0], X0[1], ALPHA, 1.0, 1.0, 1.0 / 8000)
    print("B7 collision Jacobian columns", J["columns"])
    print("    singular values", np.array2string(J["singular_values"], precision=3))
    print("    numerical rank", J["rank"])
    rec.add("B7_collision_jacobian", {"columns": J["columns"],
                                      "singular_values": J["singular_values"].tolist(),
                                      "rank": J["rank"],
                                      "note": "dx(t;p)/dp = E_alpha(A t^alpha) vanishes identically "
                                              "at t=1, so the p- and q-columns are ~0: this linear "
                                              "collision is maximally degenerate in the initial "
                                              "states and only the age columns carry rank."})

    rec.add("provenance", model.provenance)
    rec.add("claim_link", "KNOWN-A02 (research/CLAIMS.md)")
    rec.add("evidence_class",
            "CERTIFIED COMPUTATION for the E_alpha zero (Krawczyk/Arb) + exact algebra for the "
            "collapse; NUMERICAL CORROBORATION for the three-solver confirmation. "
            "NOT verified against the published Cong-Tuan example (source text unavailable locally).")
    print("\nmanifest:", rec.finish())


if __name__ == "__main__":
    main()
