r"""Vector fields used by TASK-0001, with explicit provenance labels.

PROVENANCE DISCIPLINE
---------------------
``provenance`` on every model states whether the equations are

  ``PUBLISHED``           - equations reproduced from a source whose exact
                            formulation is available inside this repository;
  ``PROJECT-CONSTRUCTED`` - assembled by the Compute Agent from published
                            ingredients, *not* a reproduction of any published
                            parameterisation.

Stage C of TASK-0001 asked for Mondal et al. (2025), DOI 10.1016/j.cjph.2025.09.020.
Its equations and parameter values are **not** recoverable from anything stored
in this repository (only DOI + prose role descriptions exist), so per the task's
own stop rule no model here claims to be that model.
"""
from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

__all__ = [
    "LinearScalar",
    "ScaledRotation",
    "ScalarAllee",
    "AlleePredatorPrey",
    "DoubleAlleePredatorPrey",
]


@dataclass
class LinearScalar:
    """``^C D^a x = lam x``; exact solution ``x0 E_a(lam t^a)``."""

    lam: float = -1.0
    name: str = "linear_scalar"
    provenance: str = "PUBLISHED (textbook linear Caputo test problem)"
    d: int = 1

    def g(self, X):
        return self.lam * X

    def jac(self, X):
        M = X.shape[0]
        return np.full((M, 1, 1), self.lam)

    def g_mp(self, x):
        return [self.lam * x[0]]


@dataclass
class ScaledRotation:
    r"""``^C D^a x = A x`` with ``A = rho R(theta)``, ``R`` a plane rotation.

    Exact solution ``x(t) = E_a(A t^a) x0``, and because the algebra generated by
    ``I`` and ``J`` is isomorphic to C, ``E_a(A t^a)`` is the real 2x2 matrix
    built from ``w = E_a(rho e^{i theta} t^a)``.  Used in Stage B.
    """

    rho: float = 1.0
    theta: float = 1.0
    name: str = "scaled_rotation"
    provenance: str = "PUBLISHED (linear Caputo system); Stage-B construction is PROJECT-CONSTRUCTED"
    d: int = 2

    @property
    def A(self):
        c, s = np.cos(self.theta), np.sin(self.theta)
        return self.rho * np.array([[c, -s], [s, c]])

    def g(self, X):
        return X @ self.A.T

    def jac(self, X):
        return np.broadcast_to(self.A, (X.shape[0], 2, 2)).copy()

    def g_mp(self, x):
        import mpmath as mp

        c, s = mp.cos(self.theta), mp.sin(self.theta)
        r = mp.mpf(self.rho)
        return [r * (c * x[0] - s * x[1]), r * (s * x[0] + c * x[1])]


@dataclass
class ScalarAllee:
    r"""Area & Nieto (2023) fractional Allee logistic equation, Caputo sense:

        ^C D^a x = x (1 - x)(x - theta),   0 < theta < 1.

    Exactly the model recorded in ``research/CLAIMS.md`` (COROLLARY-S1A) and
    ``STATUS.md``; its rigorous intervalwise asymptotics come from
    Doan & Kloeden (2022).
    """

    theta: float = 0.2
    name: str = "scalar_allee"
    provenance: str = "PUBLISHED (Area & Nieto 2023; equations recorded in research/CLAIMS.md)"
    d: int = 1

    def g(self, X):
        x = X[:, 0]
        return (x * (1.0 - x) * (x - self.theta))[:, None]

    def jac(self, X):
        x = X[:, 0]
        # d/dx [ -x^3 + (1+th) x^2 - th x ]
        return (-3.0 * x**2 + 2.0 * (1.0 + self.theta) * x - self.theta).reshape(-1, 1, 1)

    def g_mp(self, x):
        return [x[0] * (1 - x[0]) * (x[0] - self.theta)]


@dataclass
class AlleePredatorPrey:
    r"""Positive planar strong-Allee predator-prey system, Caputo sense.

        ^C D^a x = x (1 - x)(x - theta) - a x y
        ^C D^a y = y (b x - m)

    PROVENANCE: **PROJECT-CONSTRUCTED**.  The prey growth term is exactly the
    published Area-Nieto (2023) strong-Allee cubic recorded in
    ``research/CLAIMS.md``; the predation and predator terms are the standard
    Lotka-Volterra pair.  No published parameterisation is being reproduced.

    Structure that matters for TASK-0001:
      * the positive cone is invariant (both components vanish on their own axis);
      * (0,0) is an extinction equilibrium, locally asymptotically stable for
        every a in (0,1) because its eigenvalues are -theta and -m;
      * (theta,0) and (1,0) are prey-only equilibria;
      * coexistence at x* = m/b, y* = (1-x*)(x*-theta)/a, which exists iff
        theta < x* < 1 and is locally asymptotically stable for the Caputo
        system whenever theta < x* and x* > (1+theta)/2 (negative trace);
      * the coupling is genuinely non-triangular.
    """

    theta: float = 0.2
    a: float = 1.0
    b: float = 1.0
    m: float = 0.7
    name: str = "allee_predator_prey"
    provenance: str = (
        "PROJECT-CONSTRUCTED (Area-Nieto 2023 strong-Allee cubic + Lotka-Volterra predation); "
        "NOT a reproduction of a published parameterisation"
    )
    d: int = 2

    def g(self, X):
        x, y = X[:, 0], X[:, 1]
        gx = x * (1.0 - x) * (x - self.theta) - self.a * x * y
        gy = y * (self.b * x - self.m)
        return np.stack([gx, gy], axis=1)

    def jac(self, X):
        x, y = X[:, 0], X[:, 1]
        J = np.empty((X.shape[0], 2, 2))
        J[:, 0, 0] = -3.0 * x**2 + 2.0 * (1.0 + self.theta) * x - self.theta - self.a * y
        J[:, 0, 1] = -self.a * x
        J[:, 1, 0] = self.b * y
        J[:, 1, 1] = self.b * x - self.m
        return J

    def g_mp(self, v):
        x, y = v
        return [
            x * (1 - x) * (x - self.theta) - self.a * x * y,
            y * (self.b * x - self.m),
        ]

    # ---- analytic structure -------------------------------------------------
    @property
    def x_star(self):
        return self.m / self.b

    @property
    def y_star(self):
        xs = self.x_star
        return (1.0 - xs) * (xs - self.theta) / self.a

    def equilibria(self):
        eqs = [(0.0, 0.0), (self.theta, 0.0), (1.0, 0.0)]
        xs, ys = self.x_star, self.y_star
        if self.theta < xs < 1.0:
            eqs.append((xs, ys))
        return eqs


@dataclass
class DoubleAlleePredatorPrey:
    r"""Double-Allee variant (mate-limitation factor), Caputo sense.

        ^C D^a x = x (1 - x)(x - theta)/(x + c) - a x y
        ^C D^a y = y (b x - m)

    PROVENANCE: **PROJECT-CONSTRUCTED**.  The ``(x-theta)/(x+c)`` pair of a
    strong (demographic) Allee threshold and a mate-finding Allee factor is the
    standard "double Allee" functional form of the Pal-Saha / Contreras-Aguirre
    family; no published parameterisation is reproduced.  Included only to test
    whether the Stage-D phenomenon is specific to a single functional form.
    """

    theta: float = 0.2
    c: float = 0.5
    a: float = 1.0
    b: float = 1.0
    m: float = 0.7
    name: str = "double_allee_predator_prey"
    provenance: str = "PROJECT-CONSTRUCTED (double-Allee functional form; no published parameterisation)"
    d: int = 2

    def g(self, X):
        x, y = X[:, 0], X[:, 1]
        gx = x * (1.0 - x) * (x - self.theta) / (x + self.c) - self.a * x * y
        gy = y * (self.b * x - self.m)
        return np.stack([gx, gy], axis=1)

    def jac(self, X):
        x, y = X[:, 0], X[:, 1]
        num = x * (1.0 - x) * (x - self.theta)
        dnum = -3.0 * x**2 + 2.0 * (1.0 + self.theta) * x - self.theta
        den = x + self.c
        J = np.empty((X.shape[0], 2, 2))
        J[:, 0, 0] = (dnum * den - num) / den**2 - self.a * y
        J[:, 0, 1] = -self.a * x
        J[:, 1, 0] = self.b * y
        J[:, 1, 1] = self.b * x - self.m
        return J

    def g_mp(self, v):
        x, y = v
        return [
            x * (1 - x) * (x - self.theta) / (x + self.c) - self.a * x * y,
            y * (self.b * x - self.m),
        ]

    @property
    def x_star(self):
        return self.m / self.b

    @property
    def y_star(self):
        xs = self.x_star
        return (1.0 - xs) * (xs - self.theta) / (self.a * (xs + self.c))
